version: 2
jobs:
  test:
    working_directory: /go/src/go.knocknote.io/rapidash
    docker:
    - image: circleci/golang:1.12
      environment:
        GO111MODULE: "on"
    - image: circleci/mysql:5.7
    - image: memcached:1.5
    - image: redis:5.0
    steps:
      - checkout
      - run:
          name: Download modules
          command: |
            go mod download
      - run:
          name: Install Lint tool
          command: |
            curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s v1.21.0
      - run:
          name: Run golangci-lint
          command: |
            golangci-lint run
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 30s
      - run:
          name: Run unit tests and measure coverage
          command: |
            go test -v -coverprofile=coverage.out ./...
            bash <(curl -s https://codecov.io/bash) -P ${CIRCLE_PULL_REQUEST##*/}
workflows:
  version: 2
  test:
    jobs:
      - test
